# Data Analyst 
# Education
Bachelor Of Engineering (Mecahniacl Engineering) From RTU 2012-2016
HSC form BSEB  ( Math , Science ) 2010
# Certifications 
Data Sceince And AI  from IITM Pravartak Technology Foundation in Collaboration with Intellipaat

# Work Experience 
 Data Analyst @ Crescent valves International Pvt ltd | Duration: Oct’20– March’23
Designed and Implemented ML Predictive Model to Optimize sales strategies and increase revenue across various region 
# Role and Responsibilities
• Conducted EDA to derive insights and identify trends using graphical techniques.
• Preprocessed data, utilizing Elastic net to extract key features and incorporating geodemographics and 
economics variables 
• Performed Feature engineering and added Price, Time series and promotional variables to create model ready 
data set across different region (Oman, Saudi Arabia, UAE) etc.
• Perform Data Cleaning and Feature Extraction to identify the significant performance parameters for each 
degrading KPI.
• Built and trained different models and Create bucket of models, Including Linear, ridge, lasso, Random Forest 
etc. conducted hyperparameter tuning to optimize model performance, focusing on the best results.
• Using MAPE as performance matrix, predicted Market, product, and region-specific demand 
 # Technologies and Tools Used: 
Python (Programming), SQL, Ms Excel, NumPy, Pandas, Matplotlib, Seaborn, Scikit Learn, Random Forest, Decision 
Tree, Logistic Regression

# ‘POC’s PERFORMED ON PROJECT's

# Project Name: E Commerce sales analysis.
• Objective of Project: A retail company wantsto understand that sales.
• Discerption: collect & Analyze data and then done data Cleaning and Prepared data for model training and 
Done Predictive Analysis.
• Tools/Libraries: Python (Programming), Pandas, NumPy, Matplotlib, scikit Learn, Seaborn, Linear Regression, 
Random Forest Regressor.
2. Project Name: Credit Card Froud Detection.
• Objective of Project: to predict whether a credit card transaction is fraudulent or not.
 Description: collect data and then done Dataset preparation and preprocessing, Dataset splitting, Modeling.
• Model training. Model evaluation and testing.
• Tools/Libraries: Python (Programming language), Pandas, Numpy, Matplotlib, Seaborn, Scikit Learn, Logistic 
Regression, Decision Tree classifier
 3. Project Name: Customer Demographics Report.
• Objective of Project: groups customers based on their age, income, and spending habits. Use the model to 
identify customer segments and create targeted marketing campaigns.
 • Description: data loading and then done data preparation and find clusters and then analyze data and create 
plots to visualize customer habits and create data frame with target.
• Tools/Libraries: Python (programming language), Pandas, Numpy, Matplotlib, Scikit-Learn, K-Means clustering.
